spring:
  datasource:
    url: jdbc:postgresql://db:5432/person
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  flyway:
    schemas: public